using Test
using ASTRA

@testset "ASTRA bootstrap" begin
    include("test_constants.jl")
    include("test_types.jl")
    include("test_model_contracts.jl")
    include("test_grid.jl")
    include("test_state.jl")
    include("test_microphysics_interfaces.jl")
    include("test_analytical_opacity.jl")
    include("test_analytical_nuclear.jl")
    include("test_analytical_eos.jl")
    include("test_analytical_energy_sources.jl")
    include("test_structure_equations.jl")
    include("test_boundary_conditions.jl")
    include("test_residual_scaffold.jl")
    include("test_classical_residual_rows.jl")
    include("test_jacobian_scaffold.jl")
    include("test_solve_contract.jl")
    include("test_convergence_basin.jl")
    include("test_local_derivative_validation.jl")
    include("test_block_jacobian.jl")
    include("test_jacobian_fidelity_audit.jl")
    include("test_solver_boundary_api.jl")
    include("test_solver_progress_diagnostics.jl")
    include("test_default_newton_progress.jl")
    include("test_center_asymptotic_scaling.jl")
    include("test_weighted_solver_metrics.jl")
    include("test_atmosphere_boundary_helpers.jl")
    include("test_outer_transport_boundary.jl")
    include("test_docs_structure.jl")
end
