@testset "docs structure" begin
    root = normpath(joinpath(@__DIR__, ".."))
    expected = [
        "docs/website/myst.yml",
        "docs/website/index.md",
        "docs/website/getting-started/installation.md",
        "docs/website/getting-started/quickstart.md",
        "docs/website/getting-started/developer-setup.md",
        "docs/website/architecture/overview.md",
        "docs/website/architecture/package-layout.md",
        "docs/website/architecture/data-model.md",
        "docs/website/architecture/solver-architecture.md",
        "docs/website/architecture/differentiability-strategy.md",
        "docs/website/architecture/formulation-interface.md",
        "docs/website/physics/overview.md",
        "docs/website/physics/stellar-structure.md",
        "docs/website/physics/eos.md",
        "docs/website/physics/opacity.md",
        "docs/website/physics/nuclear.md",
        "docs/website/physics/convection.md",
        "docs/website/physics/boundary-conditions.md",
        "docs/website/physics/atmosphere-and-photosphere.md",
        "docs/website/physics/stellar-structure/mass-conservation.md",
        "docs/website/physics/stellar-structure/hydrostatic-equilibrium.md",
        "docs/website/physics/stellar-structure/energy-generation.md",
        "docs/website/physics/stellar-structure/energy-transport.md",
        "docs/website/physics/stellar-structure/coupled-problem.md",
        "docs/website/physics/eos/analytical-eos.md",
        "docs/website/physics/opacity/analytical-opacity.md",
        "docs/website/physics/nuclear/analytical-burning.md",
        "docs/website/physics/convection/radiative-gradient-and-criterion-hook.md",
        "docs/website/methods/overview.md",
        "docs/website/methods/from-equations-to-residual.md",
        "docs/website/methods/staggered-mesh-and-state-layout.md",
        "docs/website/methods/residual-assembly.md",
        "docs/website/methods/jacobian-construction.md",
        "docs/website/methods/linear-solves-and-scaling.md",
        "docs/website/methods/nonlinear-step-metrics-and-globalization.md",
        "docs/website/methods/nonlinear-newton-and-backtracking.md",
        "docs/website/methods/initial-model-and-seeding.md",
        "docs/website/methods/boundary-condition-realization.md",
        "docs/website/methods/verification-and-jacobian-audits.md",
        "docs/website/methods/mesa-reference/overview.md",
        "docs/website/methods/mesa-reference/solver-scaling.md",
        "docs/website/methods/mesa-reference/boundary-conditions.md",
        "docs/website/methods/mesa-reference/mesh-and-variables.md",
        "docs/website/numerics/residuals.md",
        "docs/website/numerics/jacobians.md",
        "docs/website/numerics/nonlinear-solvers.md",
        "docs/website/numerics/linear-solvers.md",
        "docs/website/numerics/timestepping.md",
        "docs/website/numerics/diagnostics.md",
        "docs/website/formulations/classical-baseline.md",
        "docs/website/formulations/entropy-dae.md",
        "docs/website/formulations/method-comparison.md",
        "docs/website/tutorials/first-hydrostatic-model.md",
        "docs/website/tutorials/reading-the-codebase.md",
        "docs/website/tutorials/adding-a-microphysics-module.md",
        "docs/website/validation/philosophy.md",
        "docs/website/validation/hydrostatic-tests.md",
        "docs/website/validation/jacobian-checks.md",
        "docs/website/validation/solar-validation-ladder.md",
        "docs/website/validation/benchmark-plan.md",
        "docs/website/planning/roadmap.md",
        "docs/website/planning/milestones.md",
        "docs/website/planning/design-principles.md",
        "docs/website/planning/solar-first-strategy.md",
        "docs/website/planning/solver-maturity-and-globalization-roadmap.md",
        "docs/website/planning/julia-dependency-strategy.md",
        "docs/website/planning/differentiable-astra-roadmap.md",
        "docs/website/planning/migration-notes-from-stellax.md",
        "docs/website/development/development-guide.md",
        "docs/website/development/checklists.md",
        "docs/website/development/checklists/solar-first-lane.md",
        "docs/website/development/progress-summary.md",
        "docs/website/development/armijo-merit-validation-2026-03-30.md",
        "docs/website/development/transport-outer-boundary-hardening-2026-03-30.md",
        "docs/website/development/changelog.md",
        "docs/website/development/backlog.md",
        "docs/website/development/issues.md",
        "docs/website/contributing/contributing.md",
        "docs/website/contributing/coding-style.md",
        "docs/website/contributing/testing.md",
        "docs/website/contributing/documentation-style.md",
        "docs/website/glossary.md",
    ]

    @test all(path -> isfile(joinpath(root, path)), expected)

    contract_docs = Dict(
        "docs/website/index.md" => [
            "trustworthy classical stellar-structure baseline",
            "solver ownership",
            "research framework",
            "Physics",
            "Methods",
            "validated classical baseline solver",
        ],
        "docs/website/getting-started/quickstart.md" => [
            "`StellarModel`",
            "result.state.structure",
            "result.state.composition",
            "`ASTRA` package architecture",
        ],
        "docs/website/tutorials/first-hydrostatic-model.md" => [
            "result.state.structure",
            "result.state.composition",
            "result.state.evolution",
        ],
        "docs/website/tutorials/reading-the-codebase.md" => [
            "`StellarModel`",
            "`StructureState`",
            "`CompositionState`",
            "`EvolutionState`",
        ],
        "docs/website/architecture/contracts-overview.md" => [
            "`StellarModel`",
            "current public contract",
        ],
        "docs/website/architecture/state-ownership.md" => [
            "`StellarModel`",
            "internal transitional scaffold",
        ],
        "docs/website/architecture/differentiability-strategy.md" => [
            "solution map",
            "implicit-function-theorem view",
            "backend-agnostic",
        ],
        "docs/website/development/progress-summary.md" => [
            "2026-03-29",
            "`StellarModel`",
            "Next step",
            "Armijo merit globalization",
            "Armijo merit validation",
            "adaptive regularization remains deferred",
            "First classical residual minimal slice",
            "Phase 2 atmosphere contract recorded",
            "outer transport row remains one-sided to the photospheric face",
            "transport hotspot",
            "cell index",
        ],
        "docs/website/development/transport-outer-boundary-hardening-2026-03-30.md" => [
            "boundary ownership",
            "Boundary validity checks",
            "outer transport",
            "interior transport",
            "transport hotspot",
            "cell index",
            "surface-adjacent",
        ],
        "docs/website/development/armijo-merit-validation-2026-03-30.md" => [
            "accepted step count",
            "rejected trial count",
            "decrease ratio",
            "best rejected trial",
            "conditioning",
            "row-family",
        ],
        "docs/website/development/checklists.md" => [
            "developer-facing checklists",
            "Current checklists",
            "Solar-First Lane Checklist",
        ],
        "docs/website/development/checklists/solar-first-lane.md" => [
            "Solar-First Lane Checklist",
            "Tier 0 structural sanity checks implemented",
            "Entropy-DAE comparison lane",
            "eps_grav",
            "eps_nu",
            "screening",
            "degeneracy",
            "Atmosphere Phase 2 `T(\\tau)` upgrade implemented",
            "surface thermodynamic rows use the shared outer match-point helper layer",
            "outer transport row remains one-sided to the photospheric face",
        ],
        "docs/website/development/issues.md" => [
            "Active issues",
            "Classical residual convergence basin is still provisional",
            "Surface closure is now staged, not finished",
            "Evolution remains intentionally stubbed",
            "Phase 2 one-sided `T(\\tau)` atmosphere boundary",
            "outer transport row remains one-sided to the photospheric face",
            "shared outer match-point helper layer",
            "convergence basin",
        ],
        "docs/website/development/changelog.md" => [
            "first classical residual slice",
            "surface closure remains provisional",
            "differentiability strategy",
            "Phase 2 one-sided `T(\\tau)` atmosphere closure",
            "surface thermodynamic rows use the shared outer match-point helper layer",
            "outer transport row remains one-sided to the photospheric face",
        ],
        "docs/website/physics/overview.md" => [
            "Structure equations",
            "Constitutive physics",
            "Boundary conditions",
            "What is deferred",
            "../methods/overview.md",
            "chain rule with respect to the packed log variables",
        ],
        "docs/website/physics/stellar-structure.md" => [
            "Current ASTRA implementation",
            "Numerical realization in ASTRA",
            "What is deferred",
            "../methods/residual-assembly.md",
            "continuous-equation specification",
        ],
        "docs/website/physics/eos.md" => [
            "Current ASTRA implementation",
            "Numerical realization in ASTRA",
            "What is deferred",
            "analytical gas plus radiation",
            "degeneracy",
            "Coulomb",
            "flag-gated",
        ],
        "docs/website/physics/eos/analytical-eos.md" => [
            "pressure decomposition",
            "adiabatic_gradient",
            "specific heat",
            "../../methods/jacobian-construction.md",
            "chi_rho",
            "chi_T",
            "Paczynski",
            "Debye-Huckel",
        ],
        "docs/website/physics/opacity.md" => [
            "Current ASTRA implementation",
            "Numerical realization in ASTRA",
            "What is deferred",
            "H-minus",
        ],
        "docs/website/physics/opacity/analytical-opacity.md" => [
            "Rosseland",
            "dκ/dT",
            "dκ/drho",
            "../../methods/residual-assembly.md",
        ],
        "docs/website/physics/nuclear.md" => [
            "Current ASTRA implementation",
            "Numerical realization in ASTRA",
            "What is deferred",
            "PP-plus-CNO",
            "eps_grav",
            "eps_nu",
            "screening",
            "triple-alpha",
            "flag-gated",
        ],
        "docs/website/physics/nuclear/analytical-burning.md" => [
            "CNO",
            "dε/dT",
            "dε/drho",
            "../../methods/residual-assembly.md",
            "screening",
            "triple-alpha",
        ],
        "docs/website/physics/convection.md" => [
            "Current ASTRA implementation",
            "Numerical realization in ASTRA",
            "What is deferred",
            "criterion hook",
        ],
        "docs/website/physics/convection/radiative-gradient-and-criterion-hook.md" => [
            "nabla_rad",
            "nabla_ad",
            "residual still uses radiative transport",
            "../../methods/jacobian-construction.md",
        ],
        "docs/website/physics/boundary-conditions.md" => [
            "Current ASTRA implementation",
            "Numerical realization in ASTRA",
            "What is deferred",
            "Phase 2",
            "surface thermodynamic rows use the shared outer match-point helper layer",
            "outer transport row remains one-sided to the photospheric face",
            "Boundary rows own the edge equations of the global residual, but they do not own EOS, opacity, or atmosphere microphysics internals.",
            "Boundary validity checks",
        ],
        "docs/website/physics/atmosphere-and-photosphere.md" => [
            "photosphere",
            "tau = 2/3",
            "Eddington-grey",
            "Phase 2",
            "Phase 3",
            "surface thermodynamic rows use the shared outer match-point helper layer",
            "outer transport row remains one-sided to the photospheric face",
        ],
        "docs/website/physics/stellar-structure/mass-conservation.md" => [
            "dr/dm",
            "shell volume",
            "Numerical realization in ASTRA",
        ],
        "docs/website/physics/stellar-structure/hydrostatic-equilibrium.md" => [
            "dP/dm",
            "pressure support",
            "Current ASTRA implementation",
        ],
        "docs/website/physics/stellar-structure/energy-generation.md" => [
            "dL/dm",
            "eps_nuc",
            "What is deferred",
            "eps_grav",
            "eps_nu",
            "evolution history",
            "source-decomposed",
        ],
        "docs/website/physics/stellar-structure/energy-transport.md" => [
            "dT/dm",
            "radiative gradient",
            "log(T",
            "d \\log T",
            "subtracts the `\\nabla_k` pressure-difference term",
        ],
        "docs/website/physics/stellar-structure/coupled-problem.md" => [
            "boundary-value problem",
            "Jacobian",
            "placeholder closures",
            "eps_grav",
            "eps_nu",
            "evolution-owned",
        ],
        "docs/website/methods/overview.md" => [
            "solve pipeline",
            "Physics",
            "Methods",
            "../physics/overview.md",
            "mesa-reference/overview.md",
            "specification-grade",
        ],
        "docs/website/methods/from-equations-to-residual.md" => [
            "unknown vector",
            "residual vector",
            "log(radius",
            "../physics/stellar-structure.md",
            "\\frac{\\partial f}{\\partial \\log T}",
            "Normative packed-state contract",
        ],
        "docs/website/methods/staggered-mesh-and-state-layout.md" => [
            "face-centered",
            "cell-centered",
            "packed state",
            "mesa-reference/mesh-and-variables.md",
        ],
        "docs/website/methods/residual-assembly.md" => [
            "center rows",
            "interior blocks",
            "surface rows",
            "Phase 2 atmosphere closure",
            "eps_total",
            "../physics/stellar-structure/mass-conservation.md",
            "../physics/stellar-structure/energy-transport.md",
            "Normative interior residual contract",
            "R_{\\mathrm{geom},k}",
            "subtracts the `\\nabla_k` pressure-difference term",
            "inconsistent with the documented nabla meaning",
        ],
        "docs/website/methods/jacobian-construction.md" => [
            "analytic rows",
            "central differences",
            "jacobian_fidelity_audit",
            "../physics/eos.md",
            "../physics/nuclear.md",
            "packed solve variables",
            "Normative derivative-basis contract",
            "source-decomposed",
            "evolution history",
        ],
        "docs/website/methods/linear-solves-and-scaling.md" => [
            "erg/s",
            "column scaling",
            "regularized normal equations",
            "mesa-reference/solver-scaling.md",
            "Normative scaling contract",
        ],
        "docs/website/methods/nonlinear-step-metrics-and-globalization.md" => [
            "physical residual",
            "solver metrics",
            "merit-based globalization",
            "frozen-weight merit function",
            "Armijo",
            "predicted-versus-actual decrease",
            "best rejected trial",
            "accepted-step row-family attribution",
            "\\phi(x)",
            "correction weights",
            "weighted residual",
            "Open-risk checklist",
        ],
        "docs/website/methods/nonlinear-newton-and-backtracking.md" => [
            "damping",
            "accepted",
            "rejected trials",
            "Armijo sufficient decrease",
            "frozen-weight merit function",
            "Normative acceptance contract",
        ],
        "docs/website/methods/initial-model-and-seeding.md" => [
            "geometry-consistent",
            "source-matched",
            "surface-anchored",
        ],
        "docs/website/methods/boundary-condition-realization.md" => [
            "center asymptotic",
            "surface closure",
            "subtractive-cancellation",
            "../physics/boundary-conditions.md",
            "mesa-reference/boundary-conditions.md",
            "Normative center-boundary contract",
            "shared outer match-point temperature",
            "shared outer match-point pressure scale",
            "outer transport row remains one-sided to the photospheric face",
        ],
        "docs/website/methods/verification-and-jacobian-audits.md" => [
            "local derivative validation",
            "block jacobian",
            "default newton progress",
            "../physics/stellar-structure/coupled-problem.md",
        ],
        "docs/website/methods/mesa-reference/overview.md" => [
            "file-backed parity",
            "partial parity",
            "analogy only",
            "not yet proven",
        ],
        "docs/website/methods/mesa-reference/solver-scaling.md" => [
            "solver_support.f90",
            "x_scale",
            "correction_weight",
        ],
        "docs/website/methods/mesa-reference/boundary-conditions.md" => [
            "L_center",
            "R_center",
            "auto_diff_support.f90",
        ],
        "docs/website/methods/mesa-reference/mesh-and-variables.md" => [
            "star_data_step_input.inc",
            "star_data_step_work.inc",
            "i_lum",
            "auto_diff_support.f90",
            "\\partial \\rho / \\partial \\ln \\rho",
        ],
        "docs/website/numerics/residuals.md" => [
            "first classical structure equations",
            "source-decomposed",
            "Canonical guide: [Residual Assembly](../methods/residual-assembly.md)",
            "../methods/residual-assembly.md",
            "not the canonical numerical specification",
            "eps_grav",
            "eps_nu",
            "evolution-owned",
        ],
        "docs/website/numerics/jacobians.md" => [
            "Canonical guide: [Jacobian Construction](../methods/jacobian-construction.md)",
            "verified split between analytic rows",
            "../methods/jacobian-construction.md",
            "not the canonical numerical specification",
        ],
        "docs/website/numerics/linear-solvers.md" => [
            "Canonical guide: [Linear Solves and Scaling](../methods/linear-solves-and-scaling.md)",
            "linear-solver boundary",
            "../methods/linear-solves-and-scaling.md",
            "not the canonical numerical specification",
        ],
        "docs/website/numerics/nonlinear-solvers.md" => [
            "Canonical guides: [Nonlinear Step Metrics and Globalization](../methods/nonlinear-step-metrics-and-globalization.md) and [Nonlinear Newton and Backtracking](../methods/nonlinear-newton-and-backtracking.md)",
            "weighted residual",
            "360 rejected trials",
            "../methods/nonlinear-newton-and-backtracking.md",
            "not the canonical numerical specification",
        ],
        "docs/website/numerics/diagnostics.md" => [
            "Canonical guide: [Verification and Jacobian Audits](../methods/verification-and-jacobian-audits.md)",
            "../methods/verification-and-jacobian-audits.md",
            "merit history",
            "row-family merit summaries",
            "predicted-versus-actual decrease",
            "best rejected trial",
        ],
        "docs/website/myst.yml" => [
            "title: Physics",
            "title: Methods",
            "physics/overview.md",
            "physics/stellar-structure/mass-conservation.md",
            "methods/overview.md",
            "methods/nonlinear-step-metrics-and-globalization.md",
            "methods/mesa-reference/overview.md",
            "planning/solver-maturity-and-globalization-roadmap.md",
        ],
        "docs/website/planning/solver-maturity-and-globalization-roadmap.md" => [
            "future-facing solver strategy note",
            "What kind of nonlinear-solver architecture should ASTRA grow into",
            "MESA's controller is more mature and more battle-tested today",
            "merit-based globalization backbone",
            "robust classical baseline with interpretable nonlinear solver behavior",
            "row-family diagnostics",
            "Planning checklist",
        ],
        "docs/website/development/backlog.md" => [
            "Next up",
            "Queued after that",
            "Not backlog items yet",
        ],
        "docs/website/planning/differentiable-astra-roadmap.md" => [
            "backend-agnostic",
            "classical baseline",
            "Entropy-DAE later",
        ],
        "docs/website/contributing/documentation-style.md" => [
            "Use plain ASTRA when you mean the project",
            "Use `ASTRA` when you mean the Julia package",
            "`ASTRA.pack_state(...)`",
        ],
    )

    for (path, needles) in contract_docs
        content = read(joinpath(root, path), String)
        if path == "docs/website/myst.yml"
            @test occursin("title: Physics", content)
            @test occursin("title: Methods", content)
            @test !occursin("title: Numerics", content)
        end
        @test all(needle -> occursin(needle, content), needles)
    end

    checklist_contracts = Dict(
        "docs/website/physics/overview.md" => "Physics handbook checklist",
        "docs/website/physics/stellar-structure.md" => "Implementation checklist",
        "docs/website/physics/stellar-structure/energy-generation.md" => "Deferred-scope checklist",
        "docs/website/physics/boundary-conditions.md" => "Production-grade status checklist",
        "docs/website/physics/atmosphere-and-photosphere.md" => "Atmosphere roadmap checklist",
        "docs/website/physics/eos.md" => "Implementation checklist",
        "docs/website/physics/opacity.md" => "Validation checklist",
        "docs/website/physics/nuclear.md" => "Implementation checklist",
        "docs/website/physics/convection.md" => "Deferred-scope checklist",
        "docs/website/methods/overview.md" => "Methods handbook checklist",
        "docs/website/methods/from-equations-to-residual.md" => "MESA parity checklist",
        "docs/website/methods/staggered-mesh-and-state-layout.md" => "Implementation checklist",
        "docs/website/methods/residual-assembly.md" => "Deferred-scope checklist",
        "docs/website/methods/jacobian-construction.md" => "Validation checklist",
        "docs/website/methods/linear-solves-and-scaling.md" => "Open-risk checklist",
        "docs/website/methods/nonlinear-step-metrics-and-globalization.md" => "Open-risk checklist",
        "docs/website/methods/nonlinear-newton-and-backtracking.md" => "Open-risk checklist",
        "docs/website/methods/boundary-condition-realization.md" => "Production-grade status checklist",
        "docs/website/methods/verification-and-jacobian-audits.md" => "Verification checklist",
        "docs/website/methods/mesa-reference/overview.md" => "Usage checklist",
        "docs/website/methods/mesa-reference/mesh-and-variables.md" => "MESA parity checklist",
        "docs/website/methods/mesa-reference/solver-scaling.md" => "MESA parity checklist",
        "docs/website/methods/mesa-reference/boundary-conditions.md" => "MESA parity checklist",
        "docs/website/numerics/residuals.md" => "Summary checklist",
        "docs/website/numerics/jacobians.md" => "Summary checklist",
        "docs/website/numerics/linear-solvers.md" => "Summary checklist",
        "docs/website/numerics/nonlinear-solvers.md" => "Summary checklist",
        "docs/website/numerics/diagnostics.md" => "Summary checklist",
        "docs/website/validation/philosophy.md" => "Validation checklist",
        "docs/website/validation/jacobian-checks.md" => "Validation checklist",
        "docs/website/architecture/contracts-overview.md" => "Architecture checklist",
    )

    for (path, checklist_heading) in checklist_contracts
        content = read(joinpath(root, path), String)
        @test occursin(checklist_heading, content)
    end
end
